name: BreweryDistributor
version: '1.2'
main: fd.breweryDistributor.BreweryDistributor
api-version: '1.21'
author: FatDivision
depend: [BreweryX]
commands:
  fdbrew:
    description: Custom brewing command.
    usage: /fdbrew <subcommand>
    permission: fdbrew.use
    permission-message: You do not have permission to use this command.